<?php
/**
 * Dynamic Brand CSS Updater
 * This script updates the brand-colors.css file with current color settings
 */

// Include necessary files
require_once __DIR__ . '/../includes/db.php';
require_once __DIR__ . '/../includes/helpers.php';

// Get current brand colors from database
function getBrandColors() {
    $db = $GLOBALS['db'] ?? $mysqli ?? null;
    if (!$db) return null;
    
    $colors = [
        'primary' => '#fd7e14',
        'secondary' => '#6c757d', 
        'accent' => '#0d6efd'
    ];
    
    try {
        // Get brand colors from settings
        $stmt = $db->prepare("SELECT `key`, `value` FROM settings WHERE `key` IN ('brand_primary_color', 'brand_secondary_color', 'brand_accent_color')");
        $stmt->execute();
        $result = $stmt->get_result();
        
        while ($row = $result->fetch_assoc()) {
            $key = str_replace('_color', '', $row['key']);
            if (isset($colors[$key])) {
                $colors[$key] = $row['value'];
            }
        }
        $stmt->close();
    } catch (Exception $e) {
        error_log("Error getting brand colors: " . $e->getMessage());
    }
    
    return $colors;
}

// Convert hex to RGB
function hexToRgb($hex) {
    $hex = ltrim($hex, '#');
    if (strlen($hex) === 3) {
        $hex = $hex[0] . $hex[0] . $hex[1] . $hex[1] . $hex[2] . $hex[2];
    }
    
    $r = hexdec(substr($hex, 0, 2));
    $g = hexdec(substr($hex, 2, 2));
    $b = hexdec(substr($hex, 4, 2));
    
    return "$r, $g, $b";
}

// Generate CSS content
function generateBrandCSS($colors) {
    $primary = $colors['primary'] ?? '#fd7e14';
    $secondary = $colors['secondary'] ?? '#6c757d';
    $accent = $colors['accent'] ?? '#0d6efd';
    
    $primaryRgb = hexToRgb($primary);
    $secondaryRgb = hexToRgb($secondary);
    $accentRgb = hexToRgb($accent);
    
    $css = "/* Dynamic Brand Colors - Generated by Admin Settings */\n";
    $css .= "/* Last updated: " . date('Y-m-d H:i:s') . " */\n\n";
    $css .= ":root {\n";
    $css .= "  /* Brand Colors */\n";
    $css .= "  --brand-primary: {$primary};\n";
    $css .= "  --brand-secondary: {$secondary};\n";
    $css .= "  --brand-accent: {$accent};\n";
    $css .= "  --brand-primary-rgb: {$primaryRgb};\n";
    $css .= "  --brand-secondary-rgb: {$secondaryRgb};\n";
    $css .= "  --brand-accent-rgb: {$accentRgb};\n";
    $css .= "}\n\n";
    
    $css .= "/* Primary Brand Elements */\n";
    $css .= ".btn-primary {\n";
    $css .= "  background-color: var(--brand-primary) !important;\n";
    $css .= "  border-color: var(--brand-primary) !important;\n";
    $css .= "}\n\n";
    
    $css .= ".btn-primary:hover {\n";
    $css .= "  background-color: var(--brand-accent) !important;\n";
    $css .= "  border-color: var(--brand-accent) !important;\n";
    $css .= "}\n\n";
    
    $css .= ".btn-orange {\n";
    $css .= "  background-color: var(--brand-primary) !important;\n";
    $css .= "  border-color: var(--brand-primary) !important;\n";
    $css .= "  color: white !important;\n";
    $css .= "}\n\n";
    
    $css .= ".btn-orange:hover {\n";
    $css .= "  background-color: var(--brand-accent) !important;\n";
    $css .= "  border-color: var(--brand-accent) !important;\n";
    $css .= "  color: white !important;\n";
    $css .= "}\n\n";
    
    $css .= "/* Header Elements */\n";
    $css .= ".hero {\n";
    $css .= "  background: linear-gradient(135deg, var(--brand-primary) 0%, var(--brand-secondary) 100%);\n";
    $css .= "}\n\n";
    
    $css .= "/* Service Cards */\n";
    $css .= ".service-card {\n";
    $css .= "  border-left: 4px solid var(--brand-primary);\n";
    $css .= "}\n\n";
    
    $css .= ".service-card:hover {\n";
    $css .= "  border-left-color: var(--brand-accent);\n";
    $css .= "}\n\n";
    
    $css .= "/* Navigation Elements */\n";
    $css .= ".nav-tabs .nav-link.active {\n";
    $css .= "  background-color: var(--brand-primary) !important;\n";
    $css .= "  border-color: var(--brand-primary) !important;\n";
    $css .= "  color: white !important;\n";
    $css .= "}\n\n";
    
    $css .= ".nav-tabs .nav-link.active:hover {\n";
    $css .= "  background-color: var(--brand-accent) !important;\n";
    $css .= "  border-color: var(--brand-accent) !important;\n";
    $css .= "  color: white !important;\n";
    $css .= "}\n\n";
    
    $css .= "/* Links */\n";
    $css .= "a {\n";
    $css .= "  color: var(--brand-primary);\n";
    $css .= "}\n\n";
    
    $css .= "a:hover {\n";
    $css .= "  color: var(--brand-accent);\n";
    $css .= "}\n\n";
    
    $css .= "/* Form Elements */\n";
    $css .= ".form-control:focus {\n";
    $css .= "  border-color: var(--brand-primary);\n";
    $css .= "  box-shadow: 0 0 0 0.2rem rgba(var(--brand-primary-rgb), 0.25);\n";
    $css .= "}\n\n";
    
    $css .= "/* Admin Interface */\n";
    $css .= ".admin-header {\n";
    $css .= "  background-color: var(--brand-primary) !important;\n";
    $css .= "}\n\n";
    
    $css .= ".admin-sidebar {\n";
    $css .= "  background-color: var(--brand-secondary) !important;\n";
    $css .= "}\n\n";
    
    $css .= ".admin-sidebar .nav-link:hover {\n";
    $css .= "  background-color: var(--brand-accent) !important;\n";
    $css .= "}\n\n";
    
    $css .= "/* Footer */\n";
    $css .= ".footer {\n";
    $css .= "  background-color: var(--brand-secondary);\n";
    $css .= "  border-top: 3px solid var(--brand-primary);\n";
    $css .= "}\n\n";
    
    return $css;
}

// Update CSS file
function updateBrandCSS($colors) {
    $cssPath = __DIR__ . '/../assets/css/brand-colors.css';
    $cssContent = generateBrandCSS($colors);
    
    // Create backup of existing file
    if (file_exists($cssPath)) {
        $backupPath = str_replace('.css', '-' . date('Y-m-d-H-i-s') . '.css', $cssPath);
        copy($cssPath, $backupPath);
    }
    
    // Write new CSS content
    if (file_put_contents($cssPath, $cssContent)) {
        return true;
    }
    
    return false;
}

// Main execution
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    // Handle AJAX request from admin
    $colors = getBrandColors();
    
    if ($colors) {
        if (updateBrandCSS($colors)) {
            header('Content-Type: application/json');
            echo json_encode([
                'success' => true,
                'message' => 'Brand CSS updated successfully',
                'colors' => $colors
            ]);
        } else {
            header('Content-Type: application/json');
            echo json_encode([
                'success' => false,
                'message' => 'Failed to update CSS file'
            ]);
        }
    } else {
        header('Content-Type: application/json');
        echo json_encode([
            'success' => false,
            'message' => 'No colors found in database'
        ]);
    }
} else {
    // Direct access - update with current database colors
    $colors = getBrandColors();
    if ($colors && updateBrandCSS($colors)) {
        echo "✅ Brand CSS updated successfully!\n";
        echo "Colors: " . json_encode($colors) . "\n";
        echo "File: assets/css/brand-colors.css\n";
    } else {
        echo "❌ Failed to update brand CSS\n";
    }
}
?>
